// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/jflex/cobol.flex

package jcob;

import java_cup.runtime.Symbol;

/** Lexer of a very minimal version of the Java programming language. */
/**
IDENTIFICATION DIVISION.
PROGRAM-ID. Manipulation.

DATA DIVISION.
WORKING-STORAGE SECTION.
77 a PIC 99.

SCREEN SECTION.

1 pla-res.
    2 LINE a COL 10 VALUE 'Valeur de a :'.
    2 PIC 99 FROM a.

PROCEDURE DIVISION.

MOVE 5 TO a.
DISPLAY pla-res.
ADD 2 TO a.
DISPLAY pla-res.

STOP RUN.
**/



// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class CobolLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\37\u0200\1\u0300\u10de\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\4\0\1\5\2\0\1\6\2\0\1\7"+
    "\1\10\1\0\1\11\11\12\7\0\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\14\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\14\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\14\1\40\1\14\1\0"+
    "\1\41\4\0\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\14\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\14\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\14\1\40\1\14\265\0\2\42\115\0\1\43"+
    "\u01aa\0\1\44\325\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\2\1\4\2\5\17\6"+
    "\2\1\1\7\2\10\1\11\5\6\1\0\5\6\1\0"+
    "\3\6\1\0\4\6\1\12\2\6\5\0\1\13\1\14"+
    "\1\15\1\16\1\17\1\6\1\20\3\6\2\0\4\6"+
    "\1\0\1\6\1\0\1\6\1\21\1\6\1\21\1\22"+
    "\5\6\4\0\1\6\1\23\2\6\2\0\1\6\1\0"+
    "\1\24\2\6\1\0\2\25\1\26\5\6\1\27\2\6"+
    "\5\0\1\27\3\6\2\0\1\6\1\0\2\6\1\0"+
    "\4\6\1\0\1\6\1\30\1\6\4\0\1\31\2\6"+
    "\2\0\1\6\1\0\1\6\1\0\1\6\1\0\2\6"+
    "\1\32\1\6\1\0\1\6\1\0\1\6\1\0\1\32"+
    "\1\33\1\6\1\0\1\33\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\2\6\2\34\1\6\1\0\1\6\1\0"+
    "\2\35\1\6\1\0\1\6\1\0\1\6\1\0\2\6"+
    "\2\36\1\6\1\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\1\37\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\2\40\1\6\1\0\2\41"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\2\42\1\6\1\0\1\6\1\0\1\6\1\0\2\43"+
    "\1\6\1\0\2\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[241];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\112\0\157\0\112\0\224\0\112"+
    "\0\112\0\271\0\336\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197"+
    "\0\u01bc\0\u01e1\0\u0206\0\u022b\0\u0250\0\u0275\0\u029a\0\u02bf"+
    "\0\u02e4\0\u0309\0\u032e\0\u0353\0\112\0\u0353\0\u0378\0\u039d"+
    "\0\u03c2\0\u03e7\0\u040c\0\u0431\0\u0456\0\u047b\0\u04a0\0\u04c5"+
    "\0\u04ea\0\u050f\0\u0534\0\u0559\0\u057e\0\u05a3\0\u05c8\0\u05ed"+
    "\0\u0612\0\u0637\0\u065c\0\u0103\0\u0681\0\u06a6\0\u06cb\0\u06f0"+
    "\0\u0715\0\u073a\0\u075f\0\112\0\112\0\112\0\112\0\u0103"+
    "\0\u0784\0\u0103\0\u07a9\0\u07ce\0\u07f3\0\u0818\0\u083d\0\u0862"+
    "\0\u0887\0\u08ac\0\u08d1\0\u08f6\0\u091b\0\u0940\0\u0965\0\u0103"+
    "\0\u098a\0\112\0\u0103\0\u09af\0\u09d4\0\u09f9\0\u0a1e\0\u0a43"+
    "\0\u0a68\0\u0a8d\0\u0ab2\0\u0ad7\0\u0afc\0\u0103\0\u0b21\0\u0b46"+
    "\0\u0b6b\0\u0b90\0\u0bb5\0\u0bda\0\u0103\0\u0bff\0\u0c24\0\u0c49"+
    "\0\u0103\0\112\0\u0103\0\u0c6e\0\u0c93\0\u0cb8\0\u0cdd\0\u0d02"+
    "\0\u0103\0\u0d27\0\u0d4c\0\u0d71\0\u0d96\0\u0dbb\0\u0de0\0\u0e05"+
    "\0\112\0\u0e2a\0\u0e4f\0\u0e74\0\u0e99\0\u0ebe\0\u0ee3\0\u0f08"+
    "\0\u0f2d\0\u0f52\0\u0f77\0\u0f9c\0\u0fc1\0\u0fe6\0\u100b\0\u1030"+
    "\0\u1055\0\u0103\0\u107a\0\u109f\0\u10c4\0\u10e9\0\u110e\0\u0103"+
    "\0\u1133\0\u1158\0\u117d\0\u11a2\0\u11c7\0\u11ec\0\u1211\0\u1236"+
    "\0\u125b\0\u1280\0\u12a5\0\u12ca\0\u0103\0\u12ef\0\u1314\0\u1339"+
    "\0\u135e\0\u1383\0\u13a8\0\112\0\u0103\0\u13cd\0\u13f2\0\112"+
    "\0\u1417\0\u143c\0\u1461\0\u1486\0\u14ab\0\u14d0\0\u14f5\0\u151a"+
    "\0\u0103\0\112\0\u153f\0\u1564\0\u1589\0\u15ae\0\u0103\0\112"+
    "\0\u15d3\0\u15f8\0\u161d\0\u1642\0\u1667\0\u168c\0\u16b1\0\u16d6"+
    "\0\u0103\0\112\0\u16fb\0\u1720\0\u1745\0\u176a\0\u178f\0\u17b4"+
    "\0\u17d9\0\u17fe\0\u0103\0\u1823\0\u1848\0\u186d\0\u1892\0\u18b7"+
    "\0\u18dc\0\u1901\0\u1926\0\u194b\0\u1970\0\u0103\0\112\0\u1995"+
    "\0\u19ba\0\u0103\0\112\0\u19df\0\u1a04\0\u1a29\0\u1a4e\0\u1a73"+
    "\0\u1a98\0\u1abd\0\u1ae2\0\u0103\0\112\0\u1b07\0\u1b2c\0\u1b51"+
    "\0\u1b76\0\u1b9b\0\u1bc0\0\u0103\0\112\0\u1be5\0\u1c0a\0\u0103"+
    "\0\112";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[241];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\2\6\1\7\1\3\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\2\14"+
    "\1\21\1\14\1\22\1\23\2\14\1\24\1\25\1\26"+
    "\1\27\1\14\1\30\1\31\1\14\1\3\1\32\1\33"+
    "\1\3\2\34\2\3\1\35\1\36\33\34\1\37\3\34"+
    "\47\0\1\4\42\0\2\7\1\4\1\5\41\7\11\0"+
    "\2\12\41\0\1\14\3\0\3\14\1\40\16\14\1\41"+
    "\3\14\13\0\1\14\3\0\26\14\13\0\1\14\3\0"+
    "\15\14\1\42\10\14\13\0\1\14\3\0\1\43\7\14"+
    "\1\44\15\14\1\0\1\45\11\0\1\14\3\0\14\14"+
    "\1\46\11\14\13\0\1\14\3\0\17\14\1\47\6\14"+
    "\13\0\1\14\3\0\3\14\1\50\10\14\1\51\11\14"+
    "\13\0\1\14\3\0\10\14\1\52\15\14\1\0\1\53"+
    "\11\0\1\14\3\0\15\14\1\54\10\14\13\0\1\14"+
    "\3\0\10\14\1\55\6\14\1\56\6\14\1\0\1\57"+
    "\11\0\1\14\3\0\22\14\1\60\3\14\13\0\1\14"+
    "\3\0\2\14\1\61\1\14\1\62\14\14\1\63\4\14"+
    "\13\0\1\14\3\0\15\14\1\64\10\14\13\0\1\14"+
    "\3\0\1\65\25\14\13\0\1\14\3\0\15\14\1\66"+
    "\10\14\22\0\1\67\10\0\1\70\32\0\1\71\1\0"+
    "\1\72\14\0\1\73\10\0\2\34\3\0\34\34\1\0"+
    "\3\34\4\0\1\74\22\0\1\75\2\0\1\76\1\0"+
    "\1\77\17\0\1\14\3\0\3\14\1\100\22\14\13\0"+
    "\1\14\3\0\21\14\1\101\4\14\13\0\1\14\3\0"+
    "\12\14\1\102\13\14\13\0\1\14\3\0\21\14\1\103"+
    "\4\14\13\0\1\14\3\0\20\14\1\104\2\14\1\105"+
    "\2\14\2\0\1\106\34\0\1\106\2\0\1\107\4\0"+
    "\1\106\10\0\1\14\3\0\23\14\1\110\2\14\13\0"+
    "\1\14\3\0\15\14\1\111\10\14\13\0\1\14\3\0"+
    "\4\14\1\112\21\14\13\0\1\14\3\0\20\14\1\113"+
    "\5\14\2\0\1\114\10\0\1\14\3\0\14\14\1\115"+
    "\11\14\33\0\1\116\24\0\1\14\3\0\23\14\1\117"+
    "\2\14\13\0\1\14\3\0\2\14\1\120\23\14\13\0"+
    "\1\14\3\0\15\14\1\121\10\14\21\0\1\122\36\0"+
    "\1\14\3\0\14\14\1\123\11\14\13\0\1\14\3\0"+
    "\17\14\1\124\6\14\13\0\1\14\3\0\2\14\1\125"+
    "\23\14\13\0\1\14\3\0\15\14\1\126\10\14\13\0"+
    "\1\14\3\0\12\14\1\127\13\14\13\0\1\14\3\0"+
    "\17\14\1\130\6\14\23\0\1\131\60\0\1\114\7\0"+
    "\1\114\33\0\1\132\27\0\1\133\57\0\1\134\23\0"+
    "\1\14\3\0\7\14\1\135\16\14\13\0\1\14\3\0"+
    "\1\136\25\14\13\0\1\14\3\0\16\14\1\137\7\14"+
    "\13\0\1\14\3\0\10\14\1\140\15\14\1\0\1\141"+
    "\33\0\1\142\36\0\1\141\16\0\1\141\11\0\1\14"+
    "\3\0\10\14\1\143\15\14\1\0\1\144\11\0\1\14"+
    "\3\0\13\14\1\145\12\14\13\0\1\14\3\0\14\14"+
    "\1\146\11\14\13\0\1\14\3\0\21\14\1\147\4\14"+
    "\40\0\1\150\17\0\1\14\3\0\4\14\1\151\21\14"+
    "\23\0\1\152\34\0\1\14\3\0\4\14\1\153\21\14"+
    "\13\0\1\14\3\0\2\14\1\154\3\14\1\155\17\14"+
    "\13\0\1\14\3\0\4\14\1\156\21\14\13\0\1\14"+
    "\3\0\21\14\1\157\1\160\3\14\13\0\1\14\3\0"+
    "\16\14\1\161\7\14\13\0\1\14\3\0\22\14\1\162"+
    "\3\14\13\0\1\14\3\0\11\14\1\163\14\14\3\0"+
    "\1\164\27\0\1\165\34\0\1\166\61\0\1\167\1\170"+
    "\40\0\1\171\22\0\1\14\3\0\15\14\1\172\10\14"+
    "\13\0\1\14\3\0\12\14\1\173\13\14\13\0\1\14"+
    "\3\0\20\14\1\174\5\14\2\0\1\175\34\0\1\175"+
    "\7\0\1\175\26\0\1\176\26\0\1\14\3\0\17\14"+
    "\1\177\6\14\36\0\1\200\21\0\1\14\3\0\21\14"+
    "\1\201\4\14\13\0\1\14\3\0\1\202\25\14\17\0"+
    "\1\203\40\0\1\14\3\0\4\14\1\204\21\14\13\0"+
    "\1\14\3\0\17\14\1\205\6\14\13\0\1\14\3\0"+
    "\4\14\1\206\21\14\13\0\1\14\3\0\10\14\1\207"+
    "\15\14\1\0\1\210\11\0\1\14\3\0\17\14\1\211"+
    "\6\14\13\0\1\14\3\0\4\14\1\212\21\14\13\0"+
    "\1\14\3\0\10\14\1\213\15\14\1\0\1\214\25\0"+
    "\1\214\16\0\1\214\36\0\1\215\27\0\1\216\50\0"+
    "\1\210\16\0\1\210\34\0\1\217\21\0\1\14\3\0"+
    "\17\14\1\220\6\14\13\0\1\14\3\0\1\221\25\14"+
    "\13\0\1\14\3\0\10\14\1\222\15\14\1\0\1\223"+
    "\25\0\1\223\16\0\1\223\15\0\1\224\40\0\1\14"+
    "\3\0\15\14\1\225\10\14\34\0\1\226\23\0\1\14"+
    "\3\0\10\14\1\227\15\14\1\0\1\230\11\0\1\14"+
    "\3\0\12\14\1\231\13\14\31\0\1\232\26\0\1\14"+
    "\3\0\3\14\1\233\22\14\13\0\1\14\3\0\1\234"+
    "\25\14\13\0\1\14\3\0\14\14\1\235\11\14\13\0"+
    "\1\14\3\0\15\14\1\236\10\14\34\0\1\237\23\0"+
    "\1\14\3\0\10\14\1\240\15\14\1\0\1\241\11\0"+
    "\1\14\3\0\14\14\1\242\11\14\33\0\1\243\40\0"+
    "\1\230\16\0\1\230\31\0\1\244\40\0\1\241\16\0"+
    "\1\241\11\0\1\14\3\0\25\14\1\245\13\0\1\14"+
    "\3\0\15\14\1\246\10\14\34\0\1\247\54\0\1\250"+
    "\13\0\1\14\3\0\14\14\1\251\11\14\33\0\1\252"+
    "\24\0\1\14\3\0\5\14\1\253\20\14\24\0\1\254"+
    "\33\0\1\14\3\0\12\14\1\255\13\14\31\0\1\256"+
    "\26\0\1\14\3\0\22\14\1\257\3\14\13\0\1\14"+
    "\3\0\13\14\1\260\12\14\13\0\1\14\3\0\14\14"+
    "\1\261\11\14\33\0\1\262\24\0\1\14\3\0\21\14"+
    "\1\263\4\14\40\0\1\264\17\0\1\14\3\0\6\14"+
    "\1\265\17\14\25\0\1\266\32\0\1\14\3\0\14\14"+
    "\1\267\11\14\33\0\1\270\24\0\1\14\3\0\13\14"+
    "\1\271\12\14\32\0\1\272\25\0\1\14\3\0\10\14"+
    "\1\273\15\14\1\0\1\274\25\0\1\274\16\0\1\274"+
    "\11\0\1\14\3\0\1\275\25\14\17\0\1\276\40\0"+
    "\1\14\3\0\17\14\1\277\6\14\13\0\1\300\3\0"+
    "\26\14\13\0\1\14\3\0\25\14\1\301\44\0\1\302"+
    "\13\0\1\303\3\0\26\14\13\0\1\304\44\0\1\14"+
    "\3\0\4\14\1\305\21\14\23\0\1\306\34\0\1\14"+
    "\3\0\2\14\1\307\23\14\21\0\1\310\36\0\1\14"+
    "\3\0\21\14\1\311\4\14\40\0\1\312\17\0\1\14"+
    "\3\0\4\14\1\313\21\14\13\0\1\14\3\0\10\14"+
    "\1\314\15\14\1\0\1\315\11\0\1\14\3\0\20\14"+
    "\1\316\5\14\2\0\1\317\34\0\1\317\7\0\1\317"+
    "\10\0\1\14\3\0\14\14\1\320\11\14\33\0\1\321"+
    "\24\0\1\14\3\0\1\322\25\14\17\0\1\323\40\0"+
    "\1\14\3\0\10\14\1\324\15\14\1\0\1\325\25\0"+
    "\1\325\16\0\1\325\11\0\1\14\3\0\3\14\1\326"+
    "\22\14\22\0\1\327\35\0\1\14\3\0\21\14\1\330"+
    "\4\14\40\0\1\331\17\0\1\14\3\0\21\14\1\332"+
    "\4\14\40\0\1\333\17\0\1\14\3\0\21\14\1\334"+
    "\4\14\40\0\1\335\17\0\1\14\3\0\15\14\1\336"+
    "\10\14\34\0\1\337\23\0\1\14\3\0\15\14\1\340"+
    "\10\14\34\0\1\341\23\0\1\14\3\0\10\14\1\342"+
    "\15\14\1\0\1\343\25\0\1\343\16\0\1\343\11\0"+
    "\1\14\3\0\14\14\1\344\11\14\33\0\1\345\24\0"+
    "\1\14\3\0\17\14\1\346\6\14\36\0\1\347\21\0"+
    "\1\14\3\0\15\14\1\350\10\14\34\0\1\351\23\0"+
    "\1\14\3\0\1\352\25\14\17\0\1\353\40\0\1\14"+
    "\3\0\14\14\1\354\11\14\33\0\1\355\24\0\1\14"+
    "\3\0\6\14\1\356\17\14\25\0\1\357\32\0\1\14"+
    "\3\0\4\14\1\360\21\14\23\0\1\361\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7215];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\1\1\1\11\1\1\2\11\23\1\1\11"+
    "\7\1\1\0\5\1\1\0\3\1\1\0\7\1\5\0"+
    "\4\11\6\1\2\0\4\1\1\0\1\1\1\0\3\1"+
    "\1\11\6\1\4\0\4\1\2\0\1\1\1\0\3\1"+
    "\1\0\1\1\1\11\11\1\5\0\1\11\3\1\2\0"+
    "\1\1\1\0\2\1\1\0\4\1\1\0\3\1\4\0"+
    "\3\1\2\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\4\1\1\0\1\1\1\0\1\1\1\0\1\11\2\1"+
    "\1\0\1\11\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\3\1\1\11\1\1\1\0\1\1\1\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\3\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[241];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CobolLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException, UnknownCharacterException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new UnknownCharacterException(yytext());
            }
            // fall through
          case 37: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 38: break;
          case 3:
            { string.setLength(0); yybegin(STRING);
            }
            // fall through
          case 39: break;
          case 4:
            { return symbol(sym.DOT);
            }
            // fall through
          case 40: break;
          case 5:
            { return symbol(sym.INTEGER_LITERAL);
            }
            // fall through
          case 41: break;
          case 6:
            { return symbol(sym.IDENTIFIER, yytext());
            }
            // fall through
          case 42: break;
          case 7:
            { string.append( yytext() );
            }
            // fall through
          case 43: break;
          case 8:
            { yybegin(YYINITIAL);
                                   return symbol(sym.STRING_LITERAL,
                                   string.toString());
            }
            // fall through
          case 44: break;
          case 9:
            { string.append('\\');
            }
            // fall through
          case 45: break;
          case 10:
            { return symbol(sym.TO);
            }
            // fall through
          case 46: break;
          case 11:
            { string.append('\"');
            }
            // fall through
          case 47: break;
          case 12:
            { string.append('\n');
            }
            // fall through
          case 48: break;
          case 13:
            { string.append('\r');
            }
            // fall through
          case 49: break;
          case 14:
            { string.append('\t');
            }
            // fall through
          case 50: break;
          case 15:
            { return symbol(sym.ADD);
            }
            // fall through
          case 51: break;
          case 16:
            { return symbol(sym.COL);
            }
            // fall through
          case 52: break;
          case 17:
            { return symbol(sym.PIC);
            }
            // fall through
          case 53: break;
          case 18:
            { return symbol(sym.RUN);
            }
            // fall through
          case 54: break;
          case 19:
            { return symbol(sym.DATA);
            }
            // fall through
          case 55: break;
          case 20:
            { return symbol(sym.FROM);
            }
            // fall through
          case 56: break;
          case 21:
            { return symbol(sym.LINE);
            }
            // fall through
          case 57: break;
          case 22:
            { return symbol(sym.MOVE);
            }
            // fall through
          case 58: break;
          case 23:
            { return symbol(sym.STOP);
            }
            // fall through
          case 59: break;
          case 24:
            { return symbol(sym.VALUE);
            }
            // fall through
          case 60: break;
          case 25:
            { return symbol(sym.AUTHOR);
            }
            // fall through
          case 61: break;
          case 26:
            { return symbol(sym.SCREEN);
            }
            // fall through
          case 62: break;
          case 27:
            { return symbol(sym.DISPLAY);
            }
            // fall through
          case 63: break;
          case 28:
            { return symbol(sym.SECTION);
            }
            // fall through
          case 64: break;
          case 29:
            { return symbol(sym.DIVISION);
            }
            // fall through
          case 65: break;
          case 30:
            { return symbol(sym.SECURITY);
            }
            // fall through
          case 66: break;
          case 31:
            { return symbol(sym.PROCEDURE);
            }
            // fall through
          case 67: break;
          case 32:
            { return symbol(sym.PROGRAMID);
            }
            // fall through
          case 68: break;
          case 33:
            { return symbol(sym.ENVIRONMENT);
            }
            // fall through
          case 69: break;
          case 34:
            { return symbol(sym.INSTALLATION);
            }
            // fall through
          case 70: break;
          case 35:
            { return symbol(sym.IDENTIFICATION);
            }
            // fall through
          case 71: break;
          case 36:
            { return symbol(sym.WORKINGSTORAGE);
            }
            // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
